<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>
	<PropertyGroup>
		<UseSharedCompilation>false</UseSharedCompilation>
	</PropertyGroup>

	<ItemGroup>
    <PackageReference Include="MediatR" Version="13.0.0" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="9.0.7" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="9.0.10">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

	<ItemGroup>
	  <ProjectReference Include="..\CodeChalengeForTest.Application\CodeChalengeForTest.Application.csproj" />
	  <ProjectReference Include="..\CodeChalengeForTest.Infrustrcture\CodeChalengeForTest.Infrustrcture.csproj" />
	</ItemGroup>

</Project>
